/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // Amazon obj= new Amazon(); //Initialize your test class
     w3WinHandle obj= new w3WinHandle();
       

        //TODO: call your test case functions one after other here
          //obj.testCase01();
         try {
            obj.testCase01();
        } catch (IOException e) {
           
            e.printStackTrace();
        }
        //END Tests


       obj.endTest(); // End your test by clearning connections and closing browser
      
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
