/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
       // TestCases tests = new TestCases(); // Initialize your test class
       Amazon obj= new Amazon();

        //TODO: call your test case functions one after other here

        obj.testCase01();

        //END Tests


        obj.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
